# Generated by Django 4.1.2 on 2022-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appoinment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=10)),
                ("date", models.DateField(max_length=10)),
                (
                    "time",
                    models.TimeField(
                        choices=[
                            ("10am to 11pm", "10am to 11pm"),
                            ("11am to 12pm", "11am to 12pm"),
                            ("2pm to 3pm", "2pm to 3pm"),
                            ("3pm to 4pm", "3pm to 4pm"),
                        ],
                        default="10am to 11pm",
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            (
                                "Emergency Medicin Specialist",
                                "Emergency Medicin Specialist",
                            ),
                            ("ENT Specialist", "ENT Specialist"),
                            ("Surgeons", "Surgeons"),
                            ("Eye Specialist", "Eye Specialist"),
                            (
                                "Scaning Testing and Others",
                                "Scaning Testing and Others",
                            ),
                        ],
                        default="Cardiologist",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
