# Generated by Django 4.1.2 on 2022-11-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mymedcity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="user",
            field=models.OneToOneField(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
