# Generated by Django 4.1.2 on 2022-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mymedcity", "0002_appoinment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("dose", models.CharField(blank=True, max_length=10, null=True)),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(blank=True, upload_to="image")),
                ("mfg_date", models.DateField(blank=True, max_length=10, null=True)),
                ("exp_date", models.DateField(blank=True, max_length=10, null=True)),
                ("mfg_lic", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
