# Generated by Django 4.1.2 on 2022-10-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("specialization", models.CharField(max_length=50)),
                ("medical_degrees", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            (
                                "Emergency Medicin Specialist",
                                "Emergency Medicin Specialist",
                            ),
                            ("ENT Specialist", "ENT Specialist"),
                            ("Surgeons", "Surgeons"),
                            ("Eye Specialist", "Eye Specialist"),
                            (
                                "Scaning Testing and Others",
                                "Scaning Testing and Others",
                            ),
                        ],
                        default="Cardiologist",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
